In [2]:
import requests
import pandas as pd

In [ ]:
username = "rob"

url = f"https://api.listenbrainz.org/1/user/{username}/listens"

response = requests.get(
    url,
    params={"count": 25},
    headers={"User-Agent": "dso576-student-project/0.1"},
    timeout=30
)

response.raise_for_status()

data = response.json()

print(data.keys())
print(data["payload"].keys())
print("Number of listens returned:", len(data["payload"]["listens"]))

dict_keys(['payload'])
dict_keys(['count', 'latest_listen_ts', 'listens', 'oldest_listen_ts', 'user_id'])
Number of listens returned: 25

In [7]:
data

{'payload': {'count': 25,
  'latest_listen_ts': 1771414109,
  'listens': [{'inserted_at': 1771414107,
    'listened_at': 1771414109,
    'recording_msid': 'fd0cad33-ea33-453b-8155-1292379277db',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artist_names': ['Röyksopp'],
      'duration_ms': 402390,
      'recording_mbid': '30d08f4c-d825-4ae1-b79c-44242cddd7c0',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 10},
     'artist_name': 'Röyksopp',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '30d08f4c-d825-4ae1-b79c-44242cddd7c0',
      'recording_name': 'Some Resolve',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/some-resolve'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/7H7RaiZoTNPwjNLygV4fXQ'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299817'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/some-resolve'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062918'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Some Resolve'},
    'user_name': 'rob'},
   {'inserted_at': 1771413900,
    'listened_at': 1771413706,
    'recording_msid': 'e0f102e3-e1ea-4b24-8fa7-f7df48f80afc',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba'],
      'artist_names': ['Röyksopp', 'Susanne Sundfør'],
      'duration_ms': 326560,
      'recording_mbid': '46f0b53f-6731-457c-93e7-57cff0e5b0c2',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 9},
     'artist_name': 'Röyksopp feat. Susanne Sundfør',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' feat. '},
       {'artist_credit_name': 'Susanne Sundfør',
        'artist_mbid': 'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '46f0b53f-6731-457c-93e7-57cff0e5b0c2',
      'recording_name': 'Tell Him',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/tell-him'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/2IptkwA6pNq5DxQoP4N0AJ'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299807'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/tell-him'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062917'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Tell Him'},
    'user_name': 'rob'},
   {'inserted_at': 1771413837,
    'listened_at': 1771413380,
    'recording_msid': '067530cc-6dff-4981-8753-ebd1cb76d185',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artist_names': ['Röyksopp'],
      'duration_ms': 229690,
      'recording_mbid': 'a8eb2940-b706-4e35-afd2-f15feec4eb20',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 8},
     'artist_name': 'Röyksopp',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': 'a8eb2940-b706-4e35-afd2-f15feec4eb20',
      'recording_name': 'Remembering the Departed',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'streaming',
        'url': 'https://tidal.com/track/243062916'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/remembering-the-departed'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/remembering-the-departed'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/6RgKR5OhsoXpaj70q1bRY5'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299797'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Remembering the Departed'},
    'user_name': 'rob'},
   {'inserted_at': 1771413807,
    'listened_at': 1771413150,
    'recording_msid': '6767e940-2c06-4a15-aa4f-bccf03fca8b5',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       '90165cd6-f56e-4b26-9efa-fc30a1d05141'],
      'artist_names': ['Röyksopp', 'Pixx'],
      'duration_ms': 253000,
      'recording_mbid': '100bdac3-db86-41ba-b987-6f639914834c',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 7},
     'artist_name': 'Röyksopp feat. Pixx',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       '90165cd6-f56e-4b26-9efa-fc30a1d05141'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' feat. '},
       {'artist_credit_name': 'Pixx',
        'artist_mbid': '90165cd6-f56e-4b26-9efa-fc30a1d05141',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '100bdac3-db86-41ba-b987-6f639914834c',
      'recording_name': 'It Was a Good Thing',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/it-was-a-good-thing'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062915'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299787'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/17ONRjuKL0TH2RVhvKFiSp'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/it-was-a-good-thing'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'It Was a Good Thing'},
    'user_name': 'rob'},
   {'inserted_at': 1771413499,
    'listened_at': 1771412897,
    'recording_msid': '3965d2b1-b4ec-4a54-aff9-3c60af548941',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artist_names': ['Röyksopp'],
      'duration_ms': 373830,
      'recording_mbid': '0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 6},
     'artist_name': 'Röyksopp',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8',
      'recording_name': 'Control',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'streaming',
        'url': 'https://tidal.com/track/243062914'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/control'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/control'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/238905547'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1817573507'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/3qQFXz3qhRRa3HEXGeZ0Yl'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/4Zo9X74JIGBF6773xzBhm8'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299777'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Control'},
    'user_name': 'rob'},
   {'inserted_at': 1771412521,
    'listened_at': 1771412523,
    'recording_msid': '75e2f216-4071-49c3-b773-a424bb3edc3f',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'ba508a64-bb22-4689-8d06-ace0aac52f13'],
      'artist_names': ['Röyksopp', 'Jamie Irrepressible'],
      'duration_ms': 299920,
      'recording_mbid': '1aa80b5b-0ce3-4f5a-9a1c-67823f332a12',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 5},
     'artist_name': 'Röyksopp feat. Jamie Irrepressible',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'ba508a64-bb22-4689-8d06-ace0aac52f13'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' & '},
       {'artist_credit_name': 'Jamie Irrepressible',
        'artist_mbid': 'ba508a64-bb22-4689-8d06-ace0aac52f13',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '1aa80b5b-0ce3-4f5a-9a1c-67823f332a12',
      'recording_name': 'Sorry',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299767'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062911'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/2eVT040OQ7HXKYR5SV1WyK'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1771062137'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/230683835'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/sorry'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/sorry'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/4UpZjMN05lQTJGXQuS3sTv'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Sorry'},
    'user_name': 'rob'},
   {'inserted_at': 1771412222,
    'listened_at': 1771412223,
    'recording_msid': '89e8d7d8-56d4-4a2c-b9b1-8bb681546efc',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba'],
      'artist_names': ['Röyksopp', 'Susanne Sundfør'],
      'duration_ms': 373670,
      'recording_mbid': 'd1d936eb-fef3-4d19-8b73-419b978ede6a',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 4},
     'artist_name': 'Röyksopp feat. Susanne Sundfør',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' feat. '},
       {'artist_credit_name': 'Susanne Sundfør',
        'artist_mbid': 'f3f9e76a-0685-4a9a-97d1-6fa2b50f9fba',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': 'd1d936eb-fef3-4d19-8b73-419b978ede6a',
      'recording_name': 'Oh, Lover',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://open.spotify.com/track/2gJqvIPF8NCBmZ9Ivlj3XV'},
       {'type': 'streaming', 'url': 'https://open.qobuz.com/track/165297795'},
       {'type': 'purchase for download',
        'url': 'https://open.qobuz.com/track/165297795'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/6T1PpZV6e8YttBrK9znUIp'},
       {'type': 'streaming',
        'url': 'https://music.apple.com/no/song/1631099104'},
       {'type': 'purchase for download',
        'url': 'https://music.apple.com/no/song/1631099104'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/242763309'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062908'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/oh-lover'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299757'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/oh-lover'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/3ir8AWMPE8gcRaxwG9Yx3v'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1823142837'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/234682535'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Oh, Lover'},
    'user_name': 'rob'},
   {'inserted_at': 1771411848,
    'listened_at': 1771411849,
    'recording_msid': 'c7d0be81-702d-4a8f-a2d4-b1ffa5b2ecf0',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       '25441822-c48a-4c46-af6f-fb03339d03bb'],
      'artist_names': ['Röyksopp', 'KAREN HARDING'],
      'duration_ms': 304770,
      'recording_mbid': '07530f77-1296-43a1-aa1d-6936d7246725',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 3},
     'artist_name': 'Röyksopp feat. Karen Harding',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       '25441822-c48a-4c46-af6f-fb03339d03bb'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' feat. '},
       {'artist_credit_name': 'Karen Harding',
        'artist_mbid': '25441822-c48a-4c46-af6f-fb03339d03bb',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '07530f77-1296-43a1-aa1d-6936d7246725',
      'recording_name': 'Unity',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1773765427'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/243062907'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/0wNgwV6yNvYQyQMsdy3Kww'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/unity'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/7ARemlkf5xbKkUTper4ObM'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/unity'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/232475146'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299747'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Unity'},
    'user_name': 'rob'},
   {'inserted_at': 1771411543,
    'listened_at': 1771411545,
    'recording_msid': '3d3a05e8-faae-42bf-849b-ee915fc7299f',
    'track_metadata': {'additional_info': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'be389638-e74f-46a9-83d2-91ee3ce1fb0c'],
      'artist_names': ['Röyksopp', 'Astrid S'],
      'duration_ms': 305670,
      'recording_mbid': '8060eb6b-ca9e-4e5c-9f28-b2297b23665a',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'submission_client': 'navidrome',
      'submission_client_version': '0.58.0 (9dbe0c18)',
      'tracknumber': 2},
     'artist_name': 'Röyksopp feat. Astrid S',
     'mbid_mapping': {'artist_mbids': ['1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
       'be389638-e74f-46a9-83d2-91ee3ce1fb0c'],
      'artists': [{'artist_credit_name': 'Röyksopp',
        'artist_mbid': '1c70a3fc-fa3c-4be1-8b55-c3192db8a884',
        'join_phrase': ' feat. '},
       {'artist_credit_name': 'Astrid S',
        'artist_mbid': 'be389638-e74f-46a9-83d2-91ee3ce1fb0c',
        'join_phrase': ''}],
      'caa_id': 32916450708,
      'caa_release_mbid': 'f1418001-7f1e-46af-bfdb-95faeded8841',
      'recording_mbid': '8060eb6b-ca9e-4e5c-9f28-b2297b23665a',
      'recording_name': 'Let’s Get It Right',
      'release_group_mbid': '1d98b0bc-5832-49d2-a93e-463032631a2f',
      'release_mbid': 'e96c2e7b-94fd-4fbe-9c44-1a27d8664825',
      'url_rels': [{'type': 'streaming',
        'url': 'https://tidal.com/track/243062906'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1818071167'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/4MMzKyN1TcFpx97LqOzht2'},
       {'type': 'free streaming',
        'url': 'https://royksopp.bandcamp.com/track/let-s-get-it-right'},
       {'type': 'streaming', 'url': 'https://tidal.com/track/234678016'},
       {'type': 'purchase for download',
        'url': 'https://royksopp.bandcamp.com/track/let-s-get-it-right'},
       {'type': 'free streaming',
        'url': 'https://open.spotify.com/track/6OgGktMsglOpQBAzXWsC49'},
       {'type': 'free streaming',
        'url': 'https://www.deezer.com/track/1787299737'}]},
     'release_name': 'Profound Mysteries II',
     'track_name': 'Let’s Get It Right'},
    'user_name': 'rob'},
   {'inserted_at': 1771411238,
    'listened_at': 1771411238,
    'recording_msid': '8bf082da-de07-4df7-a7a8-7d226a2e1d2a',

In [9]:
listens = data["payload"]["listens"]

df_raw = pd.json_normalize(listens, sep="_")

df_raw.head()

,inserted_at,listened_at,recording_msid,user_name,track_metadata_additional_info_artist_mbids,track_metadata_additional_info_artist_names,track_metadata_additional_info_duration_ms,track_metadata_additional_info_recording_mbid,track_metadata_additional_info_release_group_mbid,track_metadata_additional_info_release_mbid,...,track_metadata_mbid_mapping_artists,track_metadata_mbid_mapping_caa_id,track_metadata_mbid_mapping_caa_release_mbid,track_metadata_mbid_mapping_recording_mbid,track_metadata_mbid_mapping_recording_name,track_metadata_mbid_mapping_release_group_mbid,track_metadata_mbid_mapping_release_mbid,track_metadata_mbid_mapping_url_rels,track_metadata_release_name,track_metadata_track_name
0,1771414107,1771414109,fd0cad33-ea33-453b-8155-1292379277db,rob,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],[Röyksopp],402390,30d08f4c-d825-4ae1-b79c-44242cddd7c0,1d98b0bc-5832-49d2-a93e-463032631a2f,f1418001-7f1e-46af-bfdb-95faeded8841,...,"[{'artist_credit_name': 'Röyksopp', 'artist_mb...",32916450708,f1418001-7f1e-46af-bfdb-95faeded8841,30d08f4c-d825-4ae1-b79c-44242cddd7c0,Some Resolve,1d98b0bc-5832-49d2-a93e-463032631a2f,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,"[{'type': 'free streaming', 'url': 'https://ro...",Profound Mysteries II,Some Resolve
1,1771413900,1771413706,e0f102e3-e1ea-4b24-8fa7-f7df48f80afc,rob,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, f3f9e76...","[Röyksopp, Susanne Sundfør]",326560,46f0b53f-6731-457c-93e7-57cff0e5b0c2,1d98b0bc-5832-49d2-a93e-463032631a2f,f1418001-7f1e-46af-bfdb-95faeded8841,...,"[{'artist_credit_name': 'Röyksopp', 'artist_mb...",32916450708,f1418001-7f1e-46af-bfdb-95faeded8841,46f0b53f-6731-457c-93e7-57cff0e5b0c2,Tell Him,1d98b0bc-5832-49d2-a93e-463032631a2f,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,"[{'type': 'free streaming', 'url': 'https://ro...",Profound Mysteries II,Tell Him
2,1771413837,1771413380,067530cc-6dff-4981-8753-ebd1cb76d185,rob,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],[Röyksopp],229690,a8eb2940-b706-4e35-afd2-f15feec4eb20,1d98b0bc-5832-49d2-a93e-463032631a2f,f1418001-7f1e-46af-bfdb-95faeded8841,...,"[{'artist_credit_name': 'Röyksopp', 'artist_mb...",32916450708,f1418001-7f1e-46af-bfdb-95faeded8841,a8eb2940-b706-4e35-afd2-f15feec4eb20,Remembering the Departed,1d98b0bc-5832-49d2-a93e-463032631a2f,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,"[{'type': 'streaming', 'url': 'https://tidal.c...",Profound Mysteries II,Remembering the Departed
3,1771413807,1771413150,6767e940-2c06-4a15-aa4f-bccf03fca8b5,rob,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, 90165cd...","[Röyksopp, Pixx]",253000,100bdac3-db86-41ba-b987-6f639914834c,1d98b0bc-5832-49d2-a93e-463032631a2f,f1418001-7f1e-46af-bfdb-95faeded8841,...,"[{'artist_credit_name': 'Röyksopp', 'artist_mb...",32916450708,f1418001-7f1e-46af-bfdb-95faeded8841,100bdac3-db86-41ba-b987-6f639914834c,It Was a Good Thing,1d98b0bc-5832-49d2-a93e-463032631a2f,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,"[{'type': 'free streaming', 'url': 'https://ro...",Profound Mysteries II,It Was a Good Thing
4,1771413499,1771412897,3965d2b1-b4ec-4a54-aff9-3c60af548941,rob,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],[Röyksopp],373830,0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8,1d98b0bc-5832-49d2-a93e-463032631a2f,f1418001-7f1e-46af-bfdb-95faeded8841,...,"[{'artist_credit_name': 'Röyksopp', 'artist_mb...",32916450708,f1418001-7f1e-46af-bfdb-95faeded8841,0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8,Control,1d98b0bc-5832-49d2-a93e-463032631a2f,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,"[{'type': 'streaming', 'url': 'https://tidal.c...",Profound Mysteries II,Control

In [10]:
print("Shape:", df_raw.shape)

df_raw.info()

Shape: (25, 25)
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 25 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   inserted_at                                               25 non-null     int64
 1   listened_at                                               25 non-null     int64
 2   recording_msid                                            25 non-null     str
 3   user_name                                                 25 non-null     str
 4   track_metadata_additional_info_artist_mbids               25 non-null     object
 5   track_metadata_additional_info_artist_names               25 non-null     object
 6   track_metadata_additional_info_duration_ms                25 non-null     int64
 7   track_metadata_additional_info_recording_mbid             25 non-null     str
 8   track_metadata_additional_info_release_group_mbid         25 non-null     str
 9   track_metadata_additional_info_release_mbid               25 non-null     str
 10  track_metadata_additional_info_submission_client          25 non-null     str
 11  track_metadata_additional_info_submission_client_version  25 non-null     str
 12  track_metadata_additional_info_tracknumber                25 non-null     int64
 13  track_metadata_artist_name                                25 non-null     str
 14  track_metadata_mbid_mapping_artist_mbids                  25 non-null     object
 15  track_metadata_mbid_mapping_artists                       25 non-null     object
 16  track_metadata_mbid_mapping_caa_id                        25 non-null     int64
 17  track_metadata_mbid_mapping_caa_release_mbid              25 non-null     str
 18  track_metadata_mbid_mapping_recording_mbid                25 non-null     str
 19  track_metadata_mbid_mapping_recording_name                25 non-null     str
 20  track_metadata_mbid_mapping_release_group_mbid            25 non-null     str
 21  track_metadata_mbid_mapping_release_mbid                  25 non-null     str
 22  track_metadata_mbid_mapping_url_rels                      17 non-null     object
 23  track_metadata_release_name                               25 non-null     str
 24  track_metadata_track_name                                 25 non-null     str
dtypes: int64(5), object(5), str(15)
memory usage: 14.3+ KB

In [11]:
df_raw.columns.tolist()

['inserted_at',
 'listened_at',
 'recording_msid',
 'user_name',
 'track_metadata_additional_info_artist_mbids',
 'track_metadata_additional_info_artist_names',
 'track_metadata_additional_info_duration_ms',
 'track_metadata_additional_info_recording_mbid',
 'track_metadata_additional_info_release_group_mbid',
 'track_metadata_additional_info_release_mbid',
 'track_metadata_additional_info_submission_client',
 'track_metadata_additional_info_submission_client_version',
 'track_metadata_additional_info_tracknumber',
 'track_metadata_artist_name',
 'track_metadata_mbid_mapping_artist_mbids',
 'track_metadata_mbid_mapping_artists',
 'track_metadata_mbid_mapping_caa_id',
 'track_metadata_mbid_mapping_caa_release_mbid',
 'track_metadata_mbid_mapping_recording_mbid',
 'track_metadata_mbid_mapping_recording_name',
 'track_metadata_mbid_mapping_release_group_mbid',
 'track_metadata_mbid_mapping_release_mbid',
 'track_metadata_mbid_mapping_url_rels',
 'track_metadata_release_name',
 'track_metadata_track_name']

In [12]:
def extract_listen(listen, username):
    metadata = listen.get("track_metadata", {})
    additional = metadata.get("additional_info", {})
    mapping = metadata.get("mbid_mapping", {})

    return {
        "user_name": username,
        "listened_at": listen.get("listened_at"),
        "recording_msid": listen.get("recording_msid"),
        "artist_name": metadata.get("artist_name"),
        "track_name": metadata.get("track_name"),
        "release_name": metadata.get("release_name"),

        # Prefer server-resolved MusicBrainz IDs and use submitted IDs as fallback
        "artist_mbids": (
            mapping.get("artist_mbids")
            or additional.get("artist_mbids")
        ),
        "recording_mbid": (
            mapping.get("recording_mbid")
            or additional.get("recording_mbid")
        ),
        "release_mbid": (
            mapping.get("release_mbid")
            or additional.get("release_mbid")
        ),
        "release_group_mbid": (
            mapping.get("release_group_mbid")
            or additional.get("release_group_mbid")
        ),

        "duration_ms": additional.get("duration_ms"),
        "music_service": additional.get("music_service"),
        "submission_client": additional.get("submission_client")
    }

In [13]:
rows = [extract_listen(listen, username) for listen in listens]

df = pd.DataFrame(rows)

df.head()

,user_name,listened_at,recording_msid,artist_name,track_name,release_name,artist_mbids,recording_mbid,release_mbid,release_group_mbid,duration_ms,music_service,submission_client
0,rob,1771414109,fd0cad33-ea33-453b-8155-1292379277db,Röyksopp,Some Resolve,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],30d08f4c-d825-4ae1-b79c-44242cddd7c0,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,402390,None,navidrome
1,rob,1771413706,e0f102e3-e1ea-4b24-8fa7-f7df48f80afc,Röyksopp feat. Susanne Sundfør,Tell Him,Profound Mysteries II,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, f3f9e76...",46f0b53f-6731-457c-93e7-57cff0e5b0c2,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,326560,None,navidrome
2,rob,1771413380,067530cc-6dff-4981-8753-ebd1cb76d185,Röyksopp,Remembering the Departed,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],a8eb2940-b706-4e35-afd2-f15feec4eb20,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,229690,None,navidrome
3,rob,1771413150,6767e940-2c06-4a15-aa4f-bccf03fca8b5,Röyksopp feat. Pixx,It Was a Good Thing,Profound Mysteries II,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, 90165cd...",100bdac3-db86-41ba-b987-6f639914834c,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,253000,None,navidrome
4,rob,1771412897,3965d2b1-b4ec-4a54-aff9-3c60af548941,Röyksopp,Control,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,373830,None,navidrome

In [14]:
df["listened_datetime"] = pd.to_datetime(
    df["listened_at"],
    unit="s",
    utc=True
)

df["listen_date"] = df["listened_datetime"].dt.date

df.head()

,user_name,listened_at,recording_msid,artist_name,track_name,release_name,artist_mbids,recording_mbid,release_mbid,release_group_mbid,duration_ms,music_service,submission_client,listened_datetime,listen_date
0,rob,1771414109,fd0cad33-ea33-453b-8155-1292379277db,Röyksopp,Some Resolve,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],30d08f4c-d825-4ae1-b79c-44242cddd7c0,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,402390,None,navidrome,2026-02-18 11:28:29+00:00,2026-02-18
1,rob,1771413706,e0f102e3-e1ea-4b24-8fa7-f7df48f80afc,Röyksopp feat. Susanne Sundfør,Tell Him,Profound Mysteries II,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, f3f9e76...",46f0b53f-6731-457c-93e7-57cff0e5b0c2,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,326560,None,navidrome,2026-02-18 11:21:46+00:00,2026-02-18
2,rob,1771413380,067530cc-6dff-4981-8753-ebd1cb76d185,Röyksopp,Remembering the Departed,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],a8eb2940-b706-4e35-afd2-f15feec4eb20,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,229690,None,navidrome,2026-02-18 11:16:20+00:00,2026-02-18
3,rob,1771413150,6767e940-2c06-4a15-aa4f-bccf03fca8b5,Röyksopp feat. Pixx,It Was a Good Thing,Profound Mysteries II,"[1c70a3fc-fa3c-4be1-8b55-c3192db8a884, 90165cd...",100bdac3-db86-41ba-b987-6f639914834c,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,253000,None,navidrome,2026-02-18 11:12:30+00:00,2026-02-18
4,rob,1771412897,3965d2b1-b4ec-4a54-aff9-3c60af548941,Röyksopp,Control,Profound Mysteries II,[1c70a3fc-fa3c-4be1-8b55-c3192db8a884],0228a5f7-fd54-4b8c-8d7c-7c6f2d0163b8,e96c2e7b-94fd-4fbe-9c44-1a27d8664825,1d98b0bc-5832-49d2-a93e-463032631a2f,373830,None,navidrome,2026-02-18 11:08:17+00:00,2026-02-18

In [16]:
print("Rows and columns:", df.shape)
print("Users:", df["user_name"].nunique())
print("Artists:", df["artist_name"].nunique())
print("Tracks:", df["track_name"].nunique())
print("Earliest event:", df["listened_datetime"].min())
print("Latest event:", df["listened_datetime"].max())
print("Duplicate rows:", df.duplicated().sum())

Rows and columns: (25, 15)
Users: 1
Artists: 10
Tracks: 22
Earliest event: 2026-02-05 15:32:21+00:00
Latest event: 2026-02-18 11:28:29+00:00

TypeError: unhashable type: 'list'

In [17]:
missing_summary = (
    df.isna()
      .sum()
      .to_frame("missing_count")
      .assign(missing_percent=lambda x: x["missing_count"] / len(df) * 100)
      .sort_values("missing_percent", ascending=False)
)

missing_summary

                    missing_count  missing_percent
music_service                  25            100.0
user_name                       0              0.0
listened_at                     0              0.0
recording_msid                  0              0.0
artist_name                     0              0.0
track_name                      0              0.0
release_name                    0              0.0
artist_mbids                    0              0.0
recording_mbid                  0              0.0
release_mbid                    0              0.0
release_group_mbid              0              0.0
duration_ms                     0              0.0
submission_client               0              0.0
listened_datetime               0              0.0
listen_date                     0              0.0

In [18]:
df["artist_name"].value_counts().head(10)

artist_name
B-Tribe                               8
Röyksopp                              5
Röyksopp feat. Susanne Sundfør        3
Röyksopp feat. Astrid S               2
Christian Löffler feat. Adna          2
Röyksopp feat. Pixx                   1
Röyksopp feat. Jamie Irrepressible    1
Röyksopp feat. Karen Harding          1
Christian Löffler                     1
Christian Löffler feat. Shallou       1
Name: count, dtype: int64

In [19]:
import time


def fetch_user_listens(username, start_date, end_date):
    start_ts = int(pd.Timestamp(start_date, tz="UTC").timestamp())

    # Add one day so the complete end date is included
    end_exclusive = pd.Timestamp(end_date, tz="UTC") + pd.Timedelta(days=1)
    cursor = int(end_exclusive.timestamp())

    all_listens = []

    while True:
        url = f"https://api.listenbrainz.org/1/user/{username}/listens"

        response = requests.get(
            url,
            params={
                "count": 1000,
                "max_ts": cursor
            },
            headers={"User-Agent": "dso576-student-project/0.1"},
            timeout=30
        )

        response.raise_for_status()
        batch = response.json()["payload"]["listens"]

        if not batch:
            break

        timestamps = [
            listen["listened_at"]
            for listen in batch
            if listen.get("listened_at") is not None
        ]

        if not timestamps:
            break

        for listen in batch:
            timestamp = listen.get("listened_at")

            if timestamp is not None and start_ts <= timestamp < int(end_exclusive.timestamp()):
                all_listens.append(extract_listen(listen, username))

        oldest_timestamp = min(timestamps)

        if oldest_timestamp < start_ts:
            break

        cursor = oldest_timestamp
        time.sleep(0.2)

    return pd.DataFrame(all_listens)

In [20]:
df_rob = fetch_user_listens(
    username="rob",
    start_date="2026-06-01",
    end_date="2026-08-31"
)

print(df_rob.shape)
df_rob.head()

ReadTimeout: HTTPSConnectionPool(host='api.listenbrainz.org', port=443): Read timed out. (read timeout=30)

In [ ]:
df_rob["listened_datetime"] = pd.to_datetime(
    df_rob["listened_at"],
    unit="s",
    utc=True
)

df_rob["listen_date"] = df_rob["listened_datetime"].dt.date
df_rob["listen_month"] = df_rob["listened_datetime"].dt.to_period("M").astype(str)

In [ ]:
from pathlib import Path

Path("../data").mkdir(exist_ok=True)

df_rob.to_json(
    "../data/listenbrainz_sample.jsonl",
    orient="records",
    lines=True
)

In [ ]:
sample_path = Path("../data/listenbrainz_sample.jsonl")

print(
    "File size:",
    round(sample_path.stat().st_size / 1_000_000, 2),
    "MB"
)

In [ ]:
df.shape
df.columns.tolist()
missing_summary